### ISSUE TITLE
Elastic 7.5.1

### ISSUE THREAD

**Issue by thejavator** [opendistro-for-elasticsearch/opendistro-build#119]
Hello, 
I have just seen that you have released version 1.6 that supports Elastic v7.6. Is there any version that supports 7.5.1? 
I have Elastic 7.5.1 installed and tried to installa release 1.6 but requires java 11.
Is there any solution for this? 
Thanks in advance

**Comment by alolita** [comment]
Hi @thejavator We do not currently have a Open Distro version released for 7.5.1. What version of Java are you using? Can you provide more details on what issues you're running into. Thanks.

**Comment by thejavator** [comment]
Hello, 
Thank you for your response. Here is the error showing when trying to install alerting plugin : 

`$ /usr/share/elasticsearch/bin/elasticsearch-plugin install file:/tmp/opendistro_alerting-1.7.0.0.zip
`
```
future versions of Elasticsearch will require Java 11; your Java version from [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64/jre] does not meet this requirement
-> Downloading file:/tmp/opendistro_alerting-1.7.0.0.zip
[=================================================] 100%  
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [opendistro_alerting] was built for Elasticsearch version 7.6.1 but version 7.5.1 is running
        at org.elasticsearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:346)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:728)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:803)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:786)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:232)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

```
I'm using Elastic v7.5.1 with Java 8. Is there a version of OpenDistro compatible with this configuration? 
Thanks in advance

**Comment by peterzhuamazon** [comment]
Hi @thejavator,

Sadly we do not have a ODFE version that support ES 7.5.1 version right now.
https://opendistro.github.io/for-elasticsearch-docs/version-history/
https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/

As you can see in our release history, there is a gap between the 1.4.0 and 1.6.0 as we try to catch up with the release from elastic.co. We have proceeded with the latest ES oss release at the time for ODFE 1.6.0 release, as you can see in the elastic.co website.
https://www.elastic.co/downloads/past-releases#elasticsearch

We are sorry for the inconvenience you are facing with this configuration.
Please let us know if there is any other thing we can help.

**Comment by alolita** [comment]
@thejavator Thanks for clarifying your dependency for Java 8. Can you open a separate issue for requesting Java 8 support and a 7.5.1 Elasticsearch-oss build? Thanks.

**Comment by weicongs-amazon** [comment]
close the issue. feel free to reopen it if you still have issue
