### ISSUE TITLE
"failed to turn off translog retention" after upgrade

### ISSUE THREAD

**Issue by gferrette** [opendistro-for-elasticsearch/opendistro-build#348]
Hello,

After upgrade Opendistro from version 1.0.2 to version 1.7.0, on nodes startup, its appearing on the logs the message below:

[2020-08-14T10:54:21,893][WARN ][o.e.i.s.IndexShard       ] [machine] [.tasks][0] failed to turn off translog retention
org.apache.lucene.store.AlreadyClosedException: engine is closed
        at org.elasticsearch.index.shard.IndexShard.getEngine(IndexShard.java:2528) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard.trimTranslog(IndexShard.java:1106) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard$3.doRun(IndexShard.java:1944) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.1.jar:7.6.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]

This message is appearing for several indices, but the indices/shards are not corrupted and they are on green state, but on every startup those messages are appearing on the logs.

Is there any way to solve this issue?

Thanks in advance.

Gabriel.

**Comment by peterzhuamazon** [comment]
Hi @gferrette, I have tried to reproduce the issue with a centos7 server running RPM upgrading from 1.0.2 to 1.7.0. However, I am not able to reproduce such issue with simple data on my ends.

From the looks of it, this seems like an issue related to upstream.

We would appreciate if you could share more information regarding your setup and logs.

Thanks.

**Comment by gferrette** [comment]
Hello @peterzhuamazon !

Thanks for replying.

This issue seems to be the same of this thread https://github.com/opendistro-for-elasticsearch/security/issues/354, but in my case it's happening on several indexes and not only on audit.
My setup is a test environment with one single node, follow below elasticsearch.yml (without certificates info):



#action.destructive_requires_name: true

script.painless.regex.enabled: true

#repositorio snapshot
path.repo: ["/tmp/backup_nodes"]

######## Start OpenDistro for Elasticsearch Security Demo Configuration ########
# WARNING: revise all the lines below before you go into production
opendistro_security.ssl.transport.pemcert_filepath: dummy.pem
opendistro_security.ssl.transport.pemkey_filepath: dummy-key.pem
opendistro_security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
opendistro_security.ssl.transport.enforce_hostname_verification: false
opendistro_security.ssl.http.enabled: false
opendistro_security.ssl.http.pemcert_filepath: dummy.pem
opendistro_security.ssl.http.pemkey_filepath: dummy-key.pem
opendistro_security.ssl.http.pemtrustedcas_filepath: root-ca.pem
#opendistro_security.allow_unsafe_democertificates: true
opendistro_security.allow_default_init_securityindex: true
opendistro_security.authcz.admin_dn:
  - 'DUMMY'
opendistro_security.nodes_dn:
  - 'DUMMY'

opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
cluster.routing.allocation.disk.threshold_enabled: false
node.max_local_storage_nodes: 3
######## End OpenDistro for Elasticsearch Security Demo Configuration ########



More logs info:

[2020-08-17T15:57:03,094][INFO ][o.e.g.GatewayService     ] [machine] recovered [27] indices into cluster_state
[2020-08-17T15:57:03,121][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [machine] Node started
[2020-08-17T15:57:03,122][INFO ][c.a.o.s.c.ConfigurationRepository] [machine] Check if .opendistro_security index exists ...
[2020-08-17T15:57:03,122][INFO ][c.a.o.s.c.ConfigurationRepository] [machine] .opendistro_security index does already exist, so we try to load the config from it
[2020-08-17T15:57:03,127][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [machine] 4 Open Distro Security modules loaded so far: [Module [type=REST_MANAGEMENT_API, implementing class=com.amazon.opendistroforelasticsearch.security.dlic.rest.api.OpenDistroSecurityRestApiActions], Module [type=DLSFLS, implementing class=com.amazon.opendistroforelasticsearch.security.configuration.OpenDistroSecurityFlsDlsIndexSearcherWrapper], Module [type=AUDITLOG, implementing class=com.amazon.opendistroforelasticsearch.security.auditlog.impl.AuditLogImpl], Module [type=MULTITENANCY, implementing class=com.amazon.opendistroforelasticsearch.security.configuration.PrivilegesInterceptorImpl]]
[2020-08-17T15:57:03,130][INFO ][c.a.o.s.c.ConfigurationRepository] [machine] Background init thread started. Install default config?: false
[2020-08-17T15:57:04,056][WARN ][o.e.i.s.IndexShard       ] [machine] [.tasks][0] failed to turn off translog retention
org.apache.lucene.store.AlreadyClosedException: engine is closed
        at org.elasticsearch.index.shard.IndexShard.getEngine(IndexShard.java:2528) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard.trimTranslog(IndexShard.java:1106) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard$3.doRun(IndexShard.java:1944) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.1.jar:7.6.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
[2020-08-17T15:57:06,429][WARN ][o.e.i.s.IndexShard       ] [machine] [.kibana_-532334581_test_1][0] failed to turn off translog retention
org.apache.lucene.store.AlreadyClosedException: engine is closed
        at org.elasticsearch.index.shard.IndexShard.getEngine(IndexShard.java:2528) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard.trimTranslog(IndexShard.java:1106) ~[elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.index.shard.IndexShard$3.doRun(IndexShard.java:1944) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.1.jar:7.6.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]

**Comment by peterzhuamazon** [comment]
Hi @gferrette after discussing with the team, we think this issue is more related to the security repo as there are already similar issues to this one. We will transfer this issue to the security repo. Thanks
