### ISSUE TITLE
Cannot use log4j KafkaAppender

### ISSUE THREAD

**Issue by dzhukov40** [opendistro-for-elasticsearch/opendistro-build#458]
**Describe the bug**
I try send audit logs to kafka by log4j KafkaAppender, but get error on startup. 
https://opendistro.github.io/for-elasticsearch-docs/docs/security/audit-logs/storage-types/

**To Reproduce**
_create file log4j2.properties:_
```
status = error

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n

appender.kafkaAudit.type = Kafka
appender.kafkaAudit.name = kafkaAudit
appender.kafkaAudit.property.type=Property
appender.kafkaAudit.property.name=bootstrap.servers
appender.kafkaAudit.property.value=localhost:9092
appender.kafkaAudit.topic=topic_name
appender.kafkaAudit.layout.type = PatternLayout
appender.kafkaAudit.layout.pattern = toooort %m%n

logger.auditTort.name = auditTort
logger.auditTort.level = info
logger.auditTort.appenderRef.kafka.ref = kafkaAudit
logger.auditTort.additivity = false

rootLogger.level = info
rootLogger.appenderRef.console.ref = console
```
_RUN:_
`docker run  -v "/tmp/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties" amazon/opendistro-for-elasticsearch:1.11.0`

(*)I made it easier to reproduce, in my configuration I still override "elasticsearch.yml" by specifying:
_elasticsearch.yml:_
```
...
  audit:
    type: log4j
    config:
      log4j:
        logger_name: auditTort
```

**Expected behavior**
I wont dont get error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/Callback
        at org.apache.logging.log4j.core.appender.mom.kafka.KafkaAppender$Builder.build(KafkaAppender.java:74)
        at org.apache.logging.log4j.core.appender.mom.kafka.KafkaAppender$Builder.build(KafkaAppender.java:51)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:123)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:959)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:899)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:236)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:129)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:354)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.producer.Callback
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 21 more
```

**Configuration (please complete the following information):**
 - amazon/opendistro-for-elasticsearch:1.11.0
 - Host Machine [MacOS]

**Comment by peterzhuamazon** [comment]
Seems like this is a bug related to opendistro_security plugin. Transfer the issue there. Thanks.
