### ISSUE TITLE
Wrong files permissions in opendistro-for-elasticsearch container 

### ISSUE THREAD

**Issue by ozsk** [opendistro-for-elasticsearch/opendistro-build#539]
Hi,
there is no repository for docker images so I think that it is the best place.

During `amazon/opendistro-for-elasticsearch` container start process there is a few warning messages which should be fixed in Dockerfile. It is about proper permissions on configuration directory and files.

```
[2019-03-20T12:05:13,377][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [es03.dev.logs.local] Directory /usr/share/elasticsearch/config has insecure file permissions (should be 0700)
[2019-03-20T12:05:13,377][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [es03.dev.logs.local] File /usr/share/elasticsearch/config/log4j2.properties has insecure file permissions (should be 0600)
[2019-03-20T12:05:13,377][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [es03.dev.logs.local] File /usr/share/elasticsearch/config/kirk.pem has insecure file permissions (should be 0600)
[2019-03-20T12:05:13,377][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [es03.dev.logs.local] File /usr/share/elasticsearch/config/esnode.pem has insecure file permissions (should be 0600)
[2019-03-20T12:05:13,377][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [es03.dev.logs.local] File /usr/share/elasticsearch/config/root-ca.pem has insecure file permissions (should be 0600)
[2019-03-20T12:05:13,377][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [es03.dev.logs.local] File /usr/share/elasticsearch/config/esnode-key.pem has insecure file permissions (should be 0600)
[2019-03-20T12:05:13,377][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [es03.dev.logs.local] File /usr/share/elasticsearch/config/kirk-key.pem has insecure file permissions (should be 0600)
```

Permission problems with certificates could be resolved when mounting own certificates. Same solution for elasticsearch.yml file (not visible in example log) or other files.

But still there is a problem with `config` directory and I think that there is no need to overwrite `log4j2.properties` file. So proper file permissions should be set in Dockerfile.

**Comment by peterzhuamazon** [comment]
Hi @ozsk this issue is already fixed:
https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/elasticsearch/docker/templates/Dockerfile.j2#L177

Thanks.

**Comment by peterzhuamazon** [comment]
Confirms that these warnings still exist in 1.12.0:
```
[2021-01-28T20:37:21,502][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [c3b5dcf4f0a2] Directory /usr/share/elasticsearch/config has insecure file permissions (should be 0700)
[2021-01-28T20:37:21,503][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [c3b5dcf4f0a2] File /usr/share/elasticsearch/config/elasticsearch.yml has insecure file permissions (should be 0600)
[2021-01-28T20:37:21,503][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [c3b5dcf4f0a2] File /usr/share/elasticsearch/config/log4j2.properties has insecure file permissions (should be 0600)
[2021-01-28T20:37:21,503][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [c3b5dcf4f0a2] File /usr/share/elasticsearch/config/esnode-key.pem has insecure file permissions (should be 0600)
[2021-01-28T20:37:21,504][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [c3b5dcf4f0a2] File /usr/share/elasticsearch/config/kirk-key.pem has insecure file permissions (should be 0600)
[2021-01-28T20:37:21,504][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [c3b5dcf4f0a2] File /usr/share/elasticsearch/config/root-ca.pem has insecure file permissions (should be 0600)
[2021-01-28T20:37:21,505][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [c3b5dcf4f0a2] File /usr/share/elasticsearch/config/kirk.pem has insecure file permissions (should be 0600)
[2021-01-28T20:37:21,505][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [c3b5dcf4f0a2] File /usr/share/elasticsearch/config/esnode.pem has insecure file permissions (should be 0600)
```
We will work on this issue. Thanks for reporting @ozsk 


As of the hash.sh permission, please open issue with opendistro security plugin repo @MMartyn 
https://github.com/opendistro-for-elasticsearch/security

Thanks.

**Comment by peterzhuamazon** [comment]
After making these changes opendistro security plugin does not work anymore due to not able to read these pem files:
```
[2021-01-28T22:45:05,854][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [61c130721ed2] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.10.0.jar:7.10.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.10.0.jar:7.10.0]
Caused by: java.lang.IllegalStateException: failed to load plugin class [com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:722) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:658) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:479) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:168) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.node.Node.<init>(Node.java:346) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.node.Node.<init>(Node.java:289) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.10.0.jar:7.10.0]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:713) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:658) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:479) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:168) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.node.Node.<init>(Node.java:346) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.node.Node.<init>(Node.java:289) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.10.0.jar:7.10.0]
	... 6 more
Caused by: org.elasticsearch.ElasticsearchSecurityException: Error while initializing transport SSL layer from PEM: ElasticsearchException[Unable to read /usr/share/elasticsearch/config/esnode.pem (/usr/share/elasticsearch/config/esnode.pem). Please make sure this files exists and is readable regarding to permissions. Property: opendistro_security.ssl.transport.pemcert_filepath]
	at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.initTransportSSLConfig(DefaultOpenDistroSecurityKeyStore.java:409) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.initSSLConfig(DefaultOpenDistroSecurityKeyStore.java:248) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.<init>(DefaultOpenDistroSecurityKeyStore.java:169) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.ssl.OpenDistroSecuritySSLPlugin.<init>(OpenDistroSecuritySSLPlugin.java:217) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin.<init>(OpenDistroSecurityPlugin.java:240) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:713) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:658) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:479) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:168) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.node.Node.<init>(Node.java:346) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.node.Node.<init>(Node.java:289) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.10.0.jar:7.10.0]
	... 6 more
```

**Comment by peterzhuamazon** [comment]
Since these are just warnings, after talking to the engineers, we will keep the current permissions as of now.
We will revisit later to see if there is other ways to fix this.

Thanks.

**Comment by peterzhuamazon** [comment]
Please feel free to re-open the issue if you have any other questions. Thanks.

**Comment by sastorsl** [comment]
Were you able to identify _why_ the plugins weren't able to open the files? Are they not running as the proper user?

**Comment by peterzhuamazon** [comment]
> Were you able to identify _why_ the plugins weren't able to open the files? Are they not running as the proper user?

Hi @sastorsl 

This is related to security plugin and we are currently moving to https://opensearch.org and https://github.com/opensearch-project. 

You can send a new issue to https://github.com/opensearch-project/security and see if the engineer their can help you with this question. Thanks.
