### ISSUE TITLE
Failed to exec spawn helper in Mac M1

### ISSUE THREAD

**Issue by ezorita** [opendistro-for-elasticsearch/opendistro-build#681]
**Describe the bug**
Docker-compose service fails to start, throwing a `Failed to exec spawn helper` Exception in a MacBook Pro with M1 processor.

**To Reproduce**
1. Create a `docker-compose.yml` file with an elasticsearch service:
```
  # ElasticSearch single-node cluster
  es-dev-node1:
    image: amazon/opendistro-for-elasticsearch:1.13.1
    container_name: es-dev
    restart: always
    environment:
      - cluster.name=es-dev
      - node.name=es-dev-node1
      - discovery.type=single-node
    ports:
      - 9200:9200
```
2. Run the service either with `docker-compose up` or `docker-compose run es-dev-node1`
3. Service crashes during startup.

**Expected behavior**
I expect the service to run normally, like in x86_64 architectures.

**Configuration (please complete the following information):**
 - MacBook Pro M1 (2020)
 - docker version: 20.10.3
 - docker-compose version: 1.28.2
 - amazon/opendistro-for-elasticsearch:1.13.0
 - Host machine: macOS 11.1 (20C69)

**Relevant information**
```
Exception in thread "main" java.io.IOException: Cannot run program "/opt/jdk/bin/java": error=0, Failed to exec spawn helper: pid: 522, exit value: 1
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
    at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:114)
    at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:88)
    at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
    at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:137)
    at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:95)
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 522, exit value: 1
    at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
    at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
    at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
    at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
    ... 6 more
```

**Comment by peterzhuamazon** [comment]
Hi @ezorita we have not officially support MacOS M1 chip at the moment.
Please be patient until we officially release it.
You can also check the progress on our road map here: https://github.com/orgs/opendistro-for-elasticsearch/projects/3

Thanks.
